import type { Book, UserProfile, AIRecommendation } from "@/types";

export const MOCK_BOOKS: Book[] = [
  {
    id: "1",
    title: "Atomic Habits",
    author: "James Clear",
    coverUrl: "https://covers.openlibrary.org/b/id/10521270-L.jpg",
    genre: ["Self-Help", "Psychology"],
    pageCount: 320,
    publishedYear: 2018,
    rating: 5,
    status: "finished",
    progress: { currentPage: 320, totalPages: 320, percentage: 100, lastUpdated: "2024-12-01" },
    addedAt: "2024-11-01",
    finishedAt: "2024-12-01",
    description:
      "Tiny Changes, Remarkable Results. No matter your goals, Atomic Habits offers a proven framework for improving every day.",
    tags: ["productivity", "habits", "psychology"],
  },
  {
    id: "2",
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    coverUrl: "https://covers.openlibrary.org/b/id/8739161-L.jpg",
    genre: ["Psychology", "Behavioral Economics"],
    pageCount: 499,
    publishedYear: 2011,
    rating: 4,
    status: "reading",
    progress: { currentPage: 234, totalPages: 499, percentage: 47, lastUpdated: "2025-01-10" },
    addedAt: "2024-12-15",
    startedAt: "2025-01-01",
    description:
      "In the highly anticipated Thinking, Fast and Slow, Kahneman takes us on a groundbreaking tour of the mind.",
    tags: ["psychology", "economics", "decision-making"],
  },
  {
    id: "3",
    title: "The Lean Startup",
    author: "Eric Ries",
    coverUrl: "https://covers.openlibrary.org/b/id/7398671-L.jpg",
    genre: ["Business", "Entrepreneurship"],
    pageCount: 336,
    publishedYear: 2011,
    rating: undefined,
    status: "want_to_read",
    addedAt: "2025-01-05",
    description:
      "The Lean Startup is a new approach being adopted across the globe, changing the way companies are built and new products are launched.",
    tags: ["startup", "business", "innovation"],
  },
  {
    id: "4",
    title: "Deep Work",
    author: "Cal Newport",
    coverUrl: "https://covers.openlibrary.org/b/id/8228691-L.jpg",
    genre: ["Self-Help", "Productivity"],
    pageCount: 296,
    publishedYear: 2016,
    rating: 4,
    status: "finished",
    progress: { currentPage: 296, totalPages: 296, percentage: 100, lastUpdated: "2024-10-15" },
    addedAt: "2024-09-01",
    finishedAt: "2024-10-15",
    description:
      "Rules for Focused Success in a Distracted World. Deep work is the ability to focus without distraction on a cognitively demanding task.",
    tags: ["productivity", "focus", "work"],
  },
  {
    id: "5",
    title: "The Psychology of Money",
    author: "Morgan Housel",
    coverUrl: "https://covers.openlibrary.org/b/id/10494219-L.jpg",
    genre: ["Finance", "Psychology"],
    pageCount: 256,
    publishedYear: 2020,
    rating: 5,
    status: "finished",
    progress: { currentPage: 256, totalPages: 256, percentage: 100, lastUpdated: "2024-08-20" },
    addedAt: "2024-07-10",
    finishedAt: "2024-08-20",
    description:
      "Timeless lessons on wealth, greed, and happiness. Doing well with money isn't necessarily about what you know.",
    tags: ["finance", "investing", "psychology"],
  },
  {
    id: "6",
    title: "Sapiens",
    author: "Yuval Noah Harari",
    coverUrl: "https://covers.openlibrary.org/b/id/8739165-L.jpg",
    genre: ["History", "Anthropology"],
    pageCount: 443,
    publishedYear: 2011,
    rating: undefined,
    status: "want_to_read",
    addedAt: "2025-01-12",
    description:
      "A Brief History of Humankind. From the Stone Age to the present, Harari traces the history and impact of Homo Sapiens.",
    tags: ["history", "humanity", "evolution"],
  },
  {
    id: "7",
    title: "The Midnight Library",
    author: "Matt Haig",
    coverUrl: "https://covers.openlibrary.org/b/id/10909258-L.jpg",
    genre: ["Fiction", "Philosophy"],
    pageCount: 288,
    publishedYear: 2020,
    rating: undefined,
    status: "reading",
    progress: { currentPage: 89, totalPages: 288, percentage: 31, lastUpdated: "2025-01-15" },
    addedAt: "2025-01-10",
    startedAt: "2025-01-12",
    description:
      "Between life and death there is a library, and within that library, the shelves go on forever. Every book represents a different life you could have lived.",
    tags: ["fiction", "philosophy", "existential"],
  },
];

export const MOCK_USER: UserProfile = {
  id: "user_1",
  clerkId: "clerk_user_1",
  username: "alexreads",
  displayName: "Alex Chen",
  avatarUrl: undefined,
  bio: "Always in the middle of a good book. 📚 Self-improvement & psychology nerd.",
  readingGoal: {
    booksPerYear: 24,
    pagesPerDay: 30,
    currentYear: 2025,
    booksCompleted: 3,
  },
  stats: {
    totalBooksRead: 47,
    totalPagesRead: 13240,
    totalReadingTime: 5860,
    currentStreak: 12,
    longestStreak: 31,
    averageRating: 4.2,
    favoriteGenre: "Psychology",
    booksThisYear: 3,
    booksThisMonth: 1,
  },
  preferences: {
    theme: "light",
    notifications: true,
    weeklyDigest: true,
    aiRecommendations: true,
  },
  joinedAt: "2024-01-15",
};

export const MOCK_RECOMMENDATIONS: AIRecommendation[] = [
  {
    id: "rec_1",
    book: {
      id: "r1",
      title: "The Midnight Library",
      author: "Matt Haig",
      coverUrl: "https://covers.openlibrary.org/b/id/10909258-L.jpg",
      genre: ["Fiction", "Philosophy"],
      pageCount: 288,
      publishedYear: 2020,
      status: "want_to_read",
      addedAt: "",
    },
    reason:
      "Based on your recent interest in existential fiction and the Echo of Silence, this explores the infinite possibilities of the lives we didn't choose.",
    confidence: 0.94,
    basedOn: ["1", "4"],
  },
  {
    id: "rec_2",
    book: {
      id: "r2",
      title: "Predictably Irrational",
      author: "Dan Ariely",
      coverUrl: "https://covers.openlibrary.org/b/id/7402931-L.jpg",
      genre: ["Psychology", "Behavioral Economics"],
      pageCount: 304,
      publishedYear: 2008,
      status: "want_to_read",
      addedAt: "",
    },
    reason: "A perfect follow-up to Thinking, Fast and Slow — explores hidden forces behind decisions.",
    confidence: 0.91,
    basedOn: ["2"],
  },
  {
    id: "rec_3",
    book: {
      id: "r3",
      title: "Zero to One",
      author: "Peter Thiel",
      coverUrl: "https://covers.openlibrary.org/b/id/8928691-L.jpg",
      genre: ["Business", "Entrepreneurship"],
      pageCount: 224,
      publishedYear: 2014,
      status: "want_to_read",
      addedAt: "",
    },
    reason: "Pairs brilliantly with The Lean Startup — a contrarian view on building the future.",
    confidence: 0.88,
    basedOn: ["3"],
  },
];
